name: loginapp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.0 
  firebase_database: ^10.2.0
  firebase_auth: ^4.4.0
  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.1.0
  google_sign_in: ^6.0.2
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/screenshots/
  fonts:
    - family: Nunito
      fonts:
        # - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
